version: '3.8'
services:
  mongodb:
    image: mongo:7.0
    container_name: erp_mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: erp_bodegas
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db